services:
  development-rw_db:
    container_name: development-rw_db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env.development
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '1'
    ports:
      - ${POSTGRES_CONTAINER_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    volumes:
      - ./db_criacao/configura_banco_de_dados_rapido/criar/init.sql:/docker-entrypoint-initdb.d/init.sql
      - development-rw_postgres:/var/lib/postgresql/data
    networks:
      - development-rw_network

  development-rw_python:
    container_name: development-rw_python
    image: python:3.11
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env.development
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '1'
    depends_on:
      - development-rw_db
    volumes:
      - .:/home/myuser/code
    networks:
      - development-rw_network

volumes:
  development-rw_postgres:

networks:
  development-rw_network:
    external: true
