"""Cria estrutura de tabela inicial.

Revision ID: 4d9a55827b32
Revises: 
Create Date: 2025-10-28 20:31:48.647871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9a55827b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atualizacoes_modulos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canais_vendas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=False),
        sa.Column('tipo', sa.String(length=63), nullable=False),
        sa.Column('situacao', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('categorias_receitas_despesas_tipo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=25), nullable=False,
                  comment='`1` Despesa\n`2` Receita\n`3` Receita e despesa'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_contabeis',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('contas_origem_situacoes',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False,
                  comment='Situações da venda:\n`0` Em aberto\n`1` Atendido\n`2` Cancelado\n`3` Em andamento\n`5` Faturado parcialmente\n`6` Atendido parcialmente\n`7` Aguardando pagamento\n`8` Pagamento confirmado\n`10` Em digitação\n`11` Verificado\n`12` Checkout parcial'),
        sa.Column('nome', sa.String(length=31), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_situacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False,
                  comment='`1` Em aberto`2` Recebido`3` Parcialmente recebido`4` Devolvido`5` Cancelado'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_tipo_ocorrencia',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=12), nullable=False,
                  comment='`1` Única\n`2` Parcelada\n`3` Mensal\n`4` Bimestral\n`5` Trimestral\n`6` Semestral\n`7` Anual\n`8` Quinzenal\n`9` Semanal'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos_classificacao',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=False,
                  comment='Fornecedor, vendedor, etc.'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id_bling'),
        sa.UniqueConstraint('nome')
    )
    op.create_table('contatos_indicador_inscricao_estadual',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=False,
                  comment='Indicador de inscrição estadual`1` Contribuinte ICMS `2` Contribuinte isento de Inscrição no cadastro de Contribuintes`9` Não Contribuinte'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )
    op.create_table('contatos_situacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=20), nullable=False,
                  comment='Situação do contato\n`A` Ativo\n`E` Excluído\n`I` Inativo\n`S` Sem movimentação'),
        sa.Column('sigla', sa.CHAR(length=1), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("sigla <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        sa.UniqueConstraint('sigla')
    )
    op.create_table('contatos_tipo',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=20), nullable=False,
                  comment='Tipo da pessoa`J` Jurídica`F` Física`E` Estrangeira'),
        sa.Column('sigla', sa.CHAR(length=1), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("sigla <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        sa.UniqueConstraint('sigla')
    )
    op.create_table('dimensoes',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('largura', sa.Integer(), nullable=False),
        sa.Column('altura', sa.Integer(), nullable=False),
        sa.Column('profundidade', sa.Integer(), nullable=False),
        sa.Column('unidade_medida', sa.Integer(), nullable=False,
                  comment='`0` Metros`1` Centímetros`2` Milímetros'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco_paises',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        comment='Bloqueio para repetir país'
    )
    op.create_table('formas_pagamento_destino',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=22), nullable=False,
                  comment='`1` Conta a receber/pagar`2` Ficha financeira`3` Caixa e bancos'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formas_pagamento_finalidade',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=26), nullable=False,
                  comment='`1` Pagamentos`2` Recebimentos`3` Pagamentos e Recebimentos'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formas_pagamento_padrao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=16), nullable=False,
                  comment='`1` Pagamentos`2` Recebimentos`3` Pagamentos e Recebimentos'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logisticas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('descricao', sa.String(length=255), nullable=False),
        sa.Column('tipo_integracao', sa.String(length=100), nullable=False),
        sa.Column('integracao_nativa', sa.Boolean(), nullable=False),
        sa.Column('situacao', sa.Boolean(), nullable=False,
                  comment='Situação do canal de venda\n`TRUE` Habilitado\n`FALSE` Desabilitado'),
        sa.Column('integracao_id', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('modulos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False),
        sa.Column('descricao', sa.String(length=120), nullable=False),
        sa.Column('criar_situacoes', sa.Boolean(), nullable=False),
        sa.CheckConstraint("descricao <> ''"),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produtos_categorias',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produtos_condicao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=17), nullable=False,
                  comment='Condição do produto`0` Não especificado`1` Novo`2` Usado'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_depositos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('descricao', sa.String(length=45), nullable=False),
        sa.Column('situacao', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False,
                  comment='`0` Inativo`1` Ativo'),
        sa.Column('padrao', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('desconsiderar_saldo', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
        sa.CheckConstraint("descricao <> ''"),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produtos_formatos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=15), nullable=False,
                  comment='Formato do produto`S` Simples`V` Com variações`E` Com composição'),
        sa.Column('sigla', sa.CHAR(length=1), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("sigla <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        sa.UniqueConstraint('sigla')
    )
    op.create_table('produtos_midias',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('tipo', sa.Boolean(), nullable=False,
                  comment='True: Foto\nFalse: Video'),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('url_miniatura', sa.Text(), nullable=True),
        sa.Column('diretorio_local', sa.Text(), nullable=True),
        sa.Column('validade', sa.DateTime(timezone=True), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_tipo_producao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=10), nullable=False,
                  comment='Tipo da produção`P` Própria`T` Terceiros'),
        sa.Column('sigla', sa.CHAR(length=1), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("sigla <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        sa.UniqueConstraint('sigla')
    )
    op.create_table('produtos_tipos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=20), nullable=False,
                  comment='Tipo do produto`S` Serviço`P` Produto`N` Serviço 06 21 22'),
        sa.Column('sigla', sa.CHAR(length=1), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("sigla <> ''"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome'),
        sa.UniqueConstraint('sigla')
    )
    op.create_table('tipos_pagamento',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=127), nullable=False,
                  comment='`1` Dinheiro`2` Cheque`3` Cartão de Crédito`4` Cartão de Débito`5` Crédito Loja`10` Vale Alimentação`11` Vale Refeição`12` Vale Presente`13` Vale Combustível`14` Duplicata Mercantil`15` Boleto Bancário`16` Depósito Bancário`17` Pagamento Instantâneo (PIX)`18` Transferência Bancária, Carteira Digital`19` Programa de Fidelidade, Cashback, Crédito Virtual`90` Sem pagamento`99` Outros'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporte_frete_por_conta_de',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=False,
                  comment='`0` Contratação do Frete por conta do Remetente (CIF)`1` Contratação do Frete por conta do Destinatário (FOB)`2` Contratação do Frete por conta de Terceiros`3` Transporte Próprio por conta do Remetente`4` Transporte Próprio por conta do Destinatário`9` Sem Ocorrência de Transporte.'),
        sa.CheckConstraint("nome <> ''"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canais_vendas_filiais',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_canal_venda', sa.BigInteger(), nullable=False),
        sa.Column('cnpj', sa.String(length=15), nullable=False),
        sa.Column('unidade_negocio', sa.Text(), nullable=False),
        sa.Column('id_deposito', sa.BigInteger(), nullable=False),
        sa.Column('padrao', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['id_canal_venda'], ['canais_vendas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_deposito'], ['produtos_depositos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_receitas_despesas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False),
        sa.Column('id_tipo', sa.Integer(), nullable=False,
                  comment="`1` Despesa`2` Receita`3` Receita e despesa'"),
        sa.Column('situacao', sa.Boolean(), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.ForeignKeyConstraint(['id_tipo'], ['categorias_receitas_despesas_tipo.id'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('contatos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('sobrenome', sa.String(length=255), nullable=False),
        sa.Column('codigo', sa.String(length=45), nullable=True),
        sa.Column('id_situacao_contato', sa.Integer(), nullable=False),
        sa.Column('numero_documento', sa.String(length=14), nullable=True,
                  comment='CPF ou CNPJ do contato'),
        sa.Column('telefone', sa.String(length=15), nullable=True,
                  comment='+5511998765432'),
        sa.Column('celular', sa.String(length=15), nullable=True,
                  comment='+5511998765432'),
        sa.Column('fantasia', sa.String(length=63), nullable=True),
        sa.Column('id_tipo_contato', sa.Integer(), nullable=False),
        sa.Column('id_indicador_inscricao_estadual', sa.Integer(), nullable=False),
        sa.Column('inscricao_estadual', sa.String(length=13), nullable=True),
        sa.Column('rg', sa.String(length=10), nullable=True),
        sa.Column('inscricao_municipal', sa.String(length=13), nullable=True),
        sa.Column('orgao_emissor', sa.String(length=55), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('data_nascimento', sa.Date(), nullable=True),
        sa.Column('sexo', sa.Integer(), nullable=False,
                  comment='1 Masculino\n2 Feminino\n3 Outro'),
        sa.Column('id_classificacao_contato', sa.BigInteger(), nullable=True),
        sa.Column('cliente_desde', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint('sexo IN (1, 2, 3)'),
        sa.ForeignKeyConstraint(['id_classificacao_contato'], ['contatos_classificacao.id_bling'], ),
        sa.ForeignKeyConstraint(['id_indicador_inscricao_estadual'], ['contatos_indicador_inscricao_estadual.id'], ),
        sa.ForeignKeyConstraint(['id_situacao_contato'], ['contatos_situacao.id'], ),
        sa.ForeignKeyConstraint(['id_tipo_contato'], ['contatos_tipo.id'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('endereco_unidade_federativa',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=True),
        sa.Column('id_pais', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_pais'], ['endereco_paises.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', 'id_pais', name='uq_uf_idpais'),
        comment='Bloqueio para repetir a mesma UF em um mesmo País'
    )
    op.create_table('formas_pagamento',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False),
        sa.Column('id_tipo_pagamento', sa.Integer(), nullable=False),
        sa.Column('situacao', sa.Boolean(), nullable=False,
                  comment="`0` Inativa\n`1` Ativa'"),
        sa.Column('fixa', sa.Boolean(), nullable=False),
        sa.Column('id_padrao', sa.Integer(), nullable=False,
                  comment='`0` Não\n`1` Padrão\n`2` Padrão devolução'),
        sa.Column('condicao', sa.String(length=127), nullable=False),
        sa.Column('id_destino', sa.Integer(), nullable=False),
        sa.Column('id_finalidade', sa.Integer(), nullable=False),
        sa.Column('taxas_aliquota', sa.Integer(), nullable=False),
        sa.Column('taxas_valor', sa.Integer(), nullable=False),
        sa.Column('taxas_prazo', sa.Integer(), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.ForeignKeyConstraint(['id_destino'], ['formas_pagamento_destino.id'], ),
        sa.ForeignKeyConstraint(['id_finalidade'], ['formas_pagamento_finalidade.id'], ),
        sa.ForeignKeyConstraint(['id_padrao'], ['formas_pagamento_padrao.id'], ),
        sa.ForeignKeyConstraint(['id_tipo_pagamento'], ['tipos_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produtos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('codigo', sa.String(length=120), nullable=False),
        sa.Column('preco', sa.Integer(), nullable=False),
        sa.Column('id_tipo_produto', sa.Integer(), server_default=sa.text('2'), nullable=False),
        sa.Column('situacao_produto', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False,
                  comment='Ação de estoque ao transformar produto Simples em Variação\n`TRUE` `Z` Irá zerar os saldos de estoque\n`FALSE` `T` Transfere o estoque do produto pai para a primeira variação informada'),
        sa.Column('id_formato_produto', sa.Integer(), nullable=False),
        sa.Column('id_produto_pai', sa.BigInteger(), nullable=True),
        sa.Column('descricao_curta', sa.Text(), nullable=True),
        sa.Column('data_validade', sa.Date(), nullable=True),
        sa.Column('unidade', sa.String(length=6), server_default='UN', nullable=True),
        sa.Column('peso_liquido', sa.Integer(), server_default=sa.text('1'), nullable=False,
                  comment='Peso líquido em KG'),
        sa.Column('peso_bruto', sa.Integer(), server_default=sa.text('1'), nullable=False,
                  comment='Peso bruto em KG'),
        sa.Column('volumes', sa.Integer(), server_default=sa.text('1'), nullable=False,
                  comment='Quantidade total de volumes que o produto precisa ser dividido para entrega'),
        sa.Column('itens_por_caixa', sa.Integer(), server_default=sa.text('1'), nullable=False,
                  comment='Quantidade de itens por caixa/embalagem'),
        sa.Column('gtin', sa.String(length=14), nullable=False,
                  comment='Código GTIN (GTIN-8, GTIN-12, GTIN-13 ou GTIN-14) do produto que está sendo comercializado'),
        sa.Column('gtin_embalagem', sa.String(length=13), nullable=True,
                  comment='Código GTIN (GTIN-8, GTIN-12 ou GTIN-13) da menor unidade comercializada no varejo'),
        sa.Column('id_tipo_producao', sa.Integer(), server_default=sa.text('1'), nullable=True),
        sa.Column('id_condicao_producao', sa.Integer(), nullable=False),
        sa.Column('frete_gratis', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False,
                  comment='Frete grátis\nValor default: `false`'),
        sa.Column('marca', sa.String(length=45), server_default='RW', nullable=False),
        sa.Column('descricao_complementar', sa.Text(), nullable=True),
        sa.Column('link_externo', sa.Text(), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('descricao_embalagem_discreta', sa.Text(), nullable=True,
                  comment='Descrição discreta do produto para utilizar na declaração de conteúdo.'),
        sa.Column('id_categoria_produto', sa.BigInteger(), nullable=False),
        sa.Column('action_estoque', sa.Boolean(), nullable=False),
        sa.Column('estoque_minimo', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('estoque_maximo', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('estoque_crossdocking', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('estoque_localizacao', sa.String(length=45), nullable=False),
        sa.Column('id_dimensoes', sa.Integer(), nullable=False),
        sa.Column('ncm', sa.String(length=10), server_default='7113.20.00', nullable=False),
        sa.Column('cest', sa.String(length=9), server_default='28.058.00', nullable=False),
        sa.Column('id_midia_principal', sa.Integer(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("cest <> ''"),
        sa.CheckConstraint("codigo <> ''"),
        sa.CheckConstraint("marca <> ''"),
        sa.CheckConstraint("ncm <> ''"),
        sa.CheckConstraint("nome <> ''"),
        sa.CheckConstraint("unidade <> ''"),
        sa.ForeignKeyConstraint(['id_categoria_produto'], ['produtos_categorias.id_bling'], ),
        sa.ForeignKeyConstraint(['id_condicao_producao'], ['produtos_condicao.id'], ),
        sa.ForeignKeyConstraint(['id_dimensoes'], ['dimensoes.id'], ),
        sa.ForeignKeyConstraint(['id_formato_produto'], ['produtos_formatos.id'], ),
        sa.ForeignKeyConstraint(['id_midia_principal'], ['produtos_midias.id'], ),
        sa.ForeignKeyConstraint(['id_produto_pai'], ['produtos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_tipo_producao'], ['produtos_tipo_producao.id'], ),
        sa.ForeignKeyConstraint(['id_tipo_produto'], ['produtos_tipos.id'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produtos_categorias_relacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_categoria_pai', sa.BigInteger(), nullable=False),
        sa.Column('id_categoria_filho', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_categoria_filho'], ['produtos_categorias.id_bling'], ),
        sa.ForeignKeyConstraint(['id_categoria_pai'], ['produtos_categorias.id_bling'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_categoria_filho')
    )
    op.create_table('situacoes',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('id_modulo', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=45), nullable=False),
        sa.Column('cor', sa.String(length=7), nullable=False),
        sa.CheckConstraint("cor <> ''"),
        sa.CheckConstraint("nome <> ''"),
        sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('borderos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('historico', sa.Text(), nullable=False),
        sa.Column('id_portador', sa.BigInteger(), nullable=False),
        sa.Column('id_categoria_receita_despesa', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_categoria_receita_despesa'], ['categorias_receitas_despesas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_portador'], ['contas_contabeis.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('categorias_receitas_despesas_relacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_categoria_pai', sa.BigInteger(), nullable=False),
        sa.Column('id_categoria_filho', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_categoria_filho'], ['categorias_receitas_despesas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_categoria_pai'], ['categorias_receitas_despesas.id_bling'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_categoria_filho')
    )
    op.create_table('contagem_estoque',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('codigo', sa.String(length=120), nullable=False),
        sa.Column('quantidade_lida', sa.Integer(), nullable=False),
        sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_produto')
    )
    op.create_table('endereco_municipios',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=True),
        sa.Column('id_uf', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_uf'], ['endereco_unidade_federativa.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', 'id_uf', name='uq_municipio_iduf'),
        comment='Bloqueio para repetir o mesmo município em um mesmo UF'
    )
    op.create_table('logistica_servicos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('descricao', sa.String(length=255), nullable=False),
        sa.Column('codigo', sa.String(length=50), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('frete_item', sa.Integer(), nullable=False),
        sa.Column('estimativa_entrega', sa.Integer(), nullable=False),
        sa.Column('id_codigo_servico', sa.String(length=100), nullable=False),
        sa.Column('logistica_id', sa.BigInteger(), nullable=False),
        sa.Column('transportador_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['logistica_id'], ['logisticas.id_bling'], ),
        sa.ForeignKeyConstraint(['transportador_id'], ['contatos.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produto_fornecedor',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('descricao', sa.String(length=150), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('preco_custo', sa.Integer(), nullable=False),
        sa.Column('preco_compra', sa.Integer(), nullable=False),
        sa.Column('padrao', sa.Boolean(), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('id_fornecedor', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_fornecedor'], ['contatos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('produto_variacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto_pai', sa.BigInteger(), nullable=False),
        sa.Column('id_produto_filho', sa.BigInteger(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('ordem', sa.Integer(), nullable=False),
        sa.Column('clone_pai', sa.Boolean(), nullable=False),
        sa.CheckConstraint("nome <> ''"),
        sa.ForeignKeyConstraint(['id_produto_filho'], ['produtos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_produto_pai'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_produto_filho')
    )
    op.create_table('produtos_estoques',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('id_deposito', sa.BigInteger(), nullable=False),
        sa.Column('saldo_fisico', sa.Integer(), nullable=False),
        sa.Column('saldo_virtual', sa.Integer(), nullable=False),
        sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.ForeignKeyConstraint(['id_deposito'], ['produtos_depositos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_midias_relacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('id_image', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_image'], ['produtos_midias.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_de_comparacao_balanco',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('id_deposito', sa.BigInteger(), nullable=False),
        sa.Column('saldo_antes', sa.Integer(), nullable=False),
        sa.Column('saldo_depois', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['id_deposito'], ['produtos_depositos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_de_estoque',
        sa.Column('id_bling', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('id_deposito', sa.BigInteger(), nullable=False),
        sa.Column('operacao', sa.CHAR(length=1), nullable=False),
        sa.Column('quantidade', sa.Integer(), nullable=False),
        sa.Column('preco', sa.Integer(), nullable=False),
        sa.Column('custo', sa.Integer(), nullable=False),
        sa.Column('observacoes', sa.String(length=100), nullable=False),
        sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.ForeignKeyConstraint(['id_deposito'], ['produtos_depositos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('vendedores',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('desconto_limite', sa.Integer(), nullable=False),
        sa.Column('id_loja', sa.Integer(), nullable=False),
        sa.Column('comissoes_desconto_maximo', sa.Integer(), nullable=False),
        sa.Column('comissoes_aliquota', sa.Integer(), nullable=False),
        sa.Column('id_contato', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_contato'], ['contatos.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('contas_receitas_despesas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('id_situacao', sa.Integer(), nullable=False),
        sa.Column('vencimento', sa.Date(), nullable=False),
        sa.Column('valor', sa.Integer(), nullable=False),
        sa.Column('id_transacao', sa.String(length=63), nullable=False),
        sa.Column('link_qr_code_pix', sa.Text(), nullable=False),
        sa.Column('link_boleto', sa.Text(), nullable=False),
        sa.Column('data_emissao', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('id_contato', sa.BigInteger(), nullable=False),
        sa.Column('id_forma_pagamento', sa.BigInteger(), nullable=False),
        sa.Column('saldo', sa.Integer(), nullable=False,
                  comment='É calculado subtraindo osvalores dos recebimentos dovalor da conta'),
        sa.Column('vencimento_original', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('numero_documento', sa.String(length=63), nullable=False,
                  comment='Número para controle interno da empresa'),
        sa.Column('competencia', sa.Date(), nullable=False),
        sa.Column('historico', sa.Text(), nullable=False,
                  comment='Descriçao da conta para controle interno da empresa'),
        sa.Column('numero_banco', sa.String(length=63), nullable=False,
                  comment='Adicionado automaticamente com o número preenchido no cadastro do banco'),
        sa.Column('id_portador', sa.BigInteger(), nullable=False),
        sa.Column('id_categoria_receita_despesa', sa.BigInteger(), nullable=False),
        sa.Column('id_vendedor', sa.BigInteger(), nullable=False),
        sa.Column('id_tipo_ocorrencia', sa.Integer(), nullable=False,
                  comment="`1` Única\n`2` Parcelada\n`3` Mensal\n`4` Bimestral\n`5` Trimestral\n`6` Semestral\n`7` Anual\n`8` Quinzenal\n`9` Semanal'"),
        sa.Column('considerar_dias_uteis', sa.Boolean(), nullable=False),
        sa.Column('dia_vencimento', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('numero_parcelas', sa.Integer(), nullable=False),
        sa.Column('data_limite', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.ForeignKeyConstraint(['id_categoria_receita_despesa'], ['categorias_receitas_despesas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_contato'], ['contatos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_forma_pagamento'], ['formas_pagamento.id_bling'], ),
        sa.ForeignKeyConstraint(['id_portador'], ['contas_contabeis.id_bling'], ),
        sa.ForeignKeyConstraint(['id_situacao'], ['contas_situacao.id'], ),
        sa.ForeignKeyConstraint(['id_tipo_ocorrencia'], ['contas_tipo_ocorrencia.id'], ),
        sa.ForeignKeyConstraint(['id_vendedor'], ['vendedores.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('endereco_bairros',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=True),
        sa.Column('id_municipio', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_municipio'], ['endereco_municipios.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', 'id_municipio', name='uq_bairro_idmunicipio'),
        comment='Bloqueio para repetir o mesmo bairro em mesmo município'
    )
    op.create_table('logistica_servico_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('servico_id', sa.BigInteger(), nullable=False),
        sa.Column('alias', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['servico_id'], ['logistica_servicos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_bordero', sa.BigInteger(), nullable=False),
        sa.Column('id_contato', sa.BigInteger(), nullable=False),
        sa.Column('numero_documento', sa.String(length=63), nullable=False),
        sa.Column('valor_pago', sa.Integer(), nullable=False),
        sa.Column('juros', sa.Integer(), nullable=False),
        sa.Column('desconto', sa.Integer(), nullable=False),
        sa.Column('acrescimo', sa.Integer(), nullable=False),
        sa.Column('tarifa', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_bordero'], ['borderos.id_bling'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_contato'], ['contatos.id_bling'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_borderos_relacao',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_conta', sa.BigInteger(), nullable=False),
        sa.Column('id_bordero', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_bordero'], ['borderos.id_bling'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_conta'], ['contas_receitas_despesas.id_bling'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_origens',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_origem', sa.BigInteger(), nullable=False),
        sa.Column('id_conta', sa.BigInteger(), nullable=False),
        sa.Column('tipo_origem', sa.String(length=63), nullable=False),
        sa.Column('numero', sa.String(length=63), nullable=False),
        sa.Column('data_emissao', sa.Date(), nullable=False),
        sa.Column('valor', sa.Integer(), nullable=False),
        sa.Column('id_conta_origem_situacao', sa.Integer(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['id_conta'], ['contas_receitas_despesas.id_bling'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_conta_origem_situacao'], ['contas_origem_situacoes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('endereco', sa.String(length=127), nullable=True),
        sa.Column('cep', sa.String(length=8), nullable=True),
        sa.Column('id_bairro', sa.Integer(), nullable=False),
        sa.Column('id_municipio', sa.Integer(), nullable=False),
        sa.Column('id_uf', sa.Integer(), nullable=False),
        sa.Column('id_pais', sa.Integer(), nullable=False),
        sa.Column('numero', sa.String(length=10), nullable=True),
        sa.Column('complemento', sa.String(length=127), nullable=True),
        sa.ForeignKeyConstraint(['id_bairro'], ['endereco_bairros.id'], ),
        sa.ForeignKeyConstraint(['id_municipio'], ['endereco_municipios.id'], ),
        sa.ForeignKeyConstraint(['id_pais'], ['endereco_paises.id'], ),
        sa.ForeignKeyConstraint(['id_uf'], ['endereco_unidade_federativa.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos_enderecos',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('id_contato', sa.BigInteger(), nullable=False),
        sa.Column('id_endereco', sa.Integer(), nullable=False),
        sa.Column('tipo_endereco', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_contato'], ['contatos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='`0`: Geral \\n `1`: Cobrança'
    )
    op.create_table('transporte_etiqueta',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('nome', sa.String(length=63), nullable=False),
        sa.Column('id_endereco', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('numero_loja', sa.String(length=45), nullable=False),
        sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False,
                  comment='Valor obrigatório caso parâmetro de geração de parcelas seja este'),
        sa.Column('data_saida', sa.Date(), server_default=sa.text('NOW()'), nullable=False,
                  comment='Valor obrigatório caso parâmetro de geração de parcelas seja este'),
        sa.Column('data_prevista', sa.Date(), nullable=False,
                  comment='Valor obrigatório caso parâmetro de geração de parcelas seja este'),
        sa.Column('id_contato', sa.BigInteger(), nullable=False),
        sa.Column('id_situacao', sa.BigInteger(), nullable=False),
        sa.Column('situacao_valor', sa.Integer(), nullable=False),
        sa.Column('id_loja', sa.Integer(), nullable=False),
        sa.Column('numero_pedido_compra', sa.String(length=45), nullable=False,
                  comment='Número da ordem de compra do pedido.'),
        sa.Column('outras_despesas', sa.Integer(), nullable=False),
        sa.Column('observacoes', sa.Text(), nullable=False),
        sa.Column('observacoes_internas', sa.Text(), nullable=False),
        sa.Column('desconto', sa.Integer(), nullable=False),
        sa.Column('desconto_unidade', sa.String(length=12), nullable=False,
                  comment='0 - Real\n1 - Percentual'),
        sa.Column('id_categoria', sa.BigInteger(), nullable=False),
        sa.Column('id_nota_fiscal', sa.BigInteger(), nullable=False),
        sa.Column('total_icms', sa.Integer(), nullable=False),
        sa.Column('total_ipi', sa.Integer(), nullable=False),
        sa.Column('id_vendedor', sa.BigInteger(), nullable=False),
        sa.Column('transporte_id_frete_por_conta', sa.Integer(), nullable=False),
        sa.Column('transporte_valor_frete', sa.Integer(), nullable=False),
        sa.Column('transporte_quantidade_volumes', sa.Integer(), nullable=False),
        sa.Column('transporte_peso_bruto', sa.Integer(), nullable=False),
        sa.Column('transporte_prazo_entrega', sa.Integer(), nullable=False),
        sa.Column('transporte_id_contato', sa.BigInteger(), nullable=False,
                  comment='transportador'),
        sa.Column('transporte_id_etiqueta', sa.Integer(), nullable=False),
        sa.Column('intermediador_cnpj', sa.String(length=14), nullable=False),
        sa.Column('intermediador_nome_usuario', sa.String(length=63), nullable=False),
        sa.Column('taxa_comissao', sa.Integer(), nullable=False,
                  comment='Taxa de comissão perante ao total da venda.'),
        sa.Column('taxa_custo_frete', sa.Integer(), nullable=False,
                  comment='Valor de custo do frete.'),
        sa.Column('taxa_valor_base', sa.Integer(), nullable=False,
                  comment='Valor base da venda para demonstrativo de cálculo das taxas via interface (Se não informado considera o total da venda).'),
        sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
        sa.ForeignKeyConstraint(['id_categoria'], ['categorias_receitas_despesas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_contato'], ['contatos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_loja'], ['canais_vendas.id_bling'], ),
        sa.ForeignKeyConstraint(['id_situacao'], ['situacoes.id_bling'], ),
        sa.ForeignKeyConstraint(['id_vendedor'], ['vendedores.id_bling'], ),
        sa.ForeignKeyConstraint(['transporte_id_contato'], ['contatos.id_bling'], ),
        sa.ForeignKeyConstraint(['transporte_id_etiqueta'], ['transporte_etiqueta.id'], ),
        sa.ForeignKeyConstraint(['transporte_id_frete_por_conta'], ['transporte_frete_por_conta_de.id'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('parcelas',
        sa.Column('id_bling', sa.BigInteger(), nullable=False,
                  comment='id contas a receber'),
        sa.Column('id_venda', sa.BigInteger(), nullable=False),
        sa.Column('data_vencimento', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('valor', sa.Integer(), nullable=False),
        sa.Column('observacoes', sa.String(length=120), nullable=False),
        sa.Column('id_forma_pagamento', sa.BigInteger(), nullable=False),
        sa.Column('id_conta_receber', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['id_conta_receber'], ['contas_receitas_despesas.id_bling'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_forma_pagamento'], ['formas_pagamento.id_bling'], ),
        sa.ForeignKeyConstraint(['id_venda'], ['vendas.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('transporte_volumes',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('id_venda', sa.BigInteger(), nullable=False),
        sa.Column('id_logistica_servico', sa.BigInteger(), nullable=False),
        sa.Column('codigo_rastreamento', sa.String(length=45), nullable=False),
        sa.ForeignKeyConstraint(['id_logistica_servico'], ['logistica_servicos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_venda'], ['vendas.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    op.create_table('vendas_itens_produtos',
        sa.Column('id_bling', sa.BigInteger(), nullable=False),
        sa.Column('id_venda', sa.BigInteger(), nullable=False),
        sa.Column('id_produto', sa.BigInteger(), nullable=False),
        sa.Column('desconto', sa.Integer(), nullable=False,
                  comment='Percentual'),
        sa.Column('valor', sa.Integer(), nullable=False,
                  comment='Valor unitário do item. Preço de lista = 4.9 (valor) + 2% (desconto)'),
        sa.Column('quantidade', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_bling'], ),
        sa.ForeignKeyConstraint(['id_venda'], ['vendas.id_bling'], ),
        sa.PrimaryKeyConstraint('id_bling')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas_itens_produtos')
    op.drop_table('transporte_volumes')
    op.drop_table('parcelas')
    op.drop_table('vendas')
    op.drop_table('transporte_etiqueta')
    op.drop_table('contatos_enderecos')
    op.drop_table('enderecos')
    op.drop_table('contas_origens')
    op.drop_table('contas_borderos_relacao')
    op.drop_table('pagamentos')
    op.drop_table('logistica_servico_aliases')
    op.drop_table('endereco_bairros')
    op.drop_table('contas_receitas_despesas')
    op.drop_table('vendedores')
    op.drop_table('registros_de_estoque')
    op.drop_table('registros_de_comparacao_balanco')
    op.drop_table('produtos_midias_relacao')
    op.drop_table('produtos_estoques')
    op.drop_table('produto_variacao')
    op.drop_table('produto_fornecedor')
    op.drop_table('logistica_servicos')
    op.drop_table('endereco_municipios')
    op.drop_table('contagem_estoque')
    op.drop_table('categorias_receitas_despesas_relacao')
    op.drop_table('borderos')
    op.drop_table('situacoes')
    op.drop_table('produtos_categorias_relacao')
    op.drop_table('produtos')
    op.drop_table('formas_pagamento')
    op.drop_table('endereco_unidade_federativa')
    op.drop_table('contatos')
    op.drop_table('categorias_receitas_despesas')
    op.drop_table('canais_vendas_filiais')
    op.drop_table('transporte_frete_por_conta_de')
    op.drop_table('tipos_pagamento')
    op.drop_table('produtos_tipos')
    op.drop_table('produtos_tipo_producao')
    op.drop_table('produtos_midias')
    op.drop_table('produtos_formatos')
    op.drop_table('produtos_depositos')
    op.drop_table('produtos_condicao')
    op.drop_table('produtos_categorias')
    op.drop_table('modulos')
    op.drop_table('logisticas')
    op.drop_table('formas_pagamento_padrao')
    op.drop_table('formas_pagamento_finalidade')
    op.drop_table('formas_pagamento_destino')
    op.drop_table('endereco_paises')
    op.drop_table('dimensoes')
    op.drop_table('contatos_tipo')
    op.drop_table('contatos_situacao')
    op.drop_table('contatos_indicador_inscricao_estadual')
    op.drop_table('contatos_classificacao')
    op.drop_table('contas_tipo_ocorrencia')
    op.drop_table('contas_situacao')
    op.drop_table('contas_origem_situacoes')
    op.drop_table('contas_contabeis')
    op.drop_table('categorias_receitas_despesas_tipo')
    op.drop_table('canais_vendas')
    op.drop_table('atualizacoes_modulos')
    # ### end Alembic commands ###
